---
- name: upgrade all yum packages
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: update yum packages
      yum:
        name: "*"
        state: latest
      register: all

    - name: print output
      debug:
        var: all

